### ISSUE TITLE
Error doing the key exchange

### ISSUE THREAD

**Issue by jajm** [tmate-io/tmate-slave#14]
Hi,

tmate works fine when I use master.tmate.io, but when I try to use it with my own server, tmate-slave answers this:

    [.........................] [tmate] FATAL Error doing the key exchange

and tmate:

    Error connecting: kex error : no match for method server host key algo: server [ssh-dss,ssh-rsa], client [ecdsa-sha2-nistp256]

When I move my ~/.ssh/known_hosts away, it works.

Any idea how I could fix this ?

**Comment by ytti** [comment]
Not sure if I'm seeing same or not. I'm running latest version from github, and tmate-slave works for me. Occasionally it crashes on 'error doing the key exchange', I presume simply because these are some port-sniffing attempts with crappy payload, case which probably is mishandled.

2015-09-03 00:05:09 [main] [tmate] Child spawned pid=6347, ip=116.54.201.188
2015-09-03 00:05:09 [.........................] [tmate] FATAL Error doing the key exchange
2015-09-03 00:05:09 [main] [tmate] Child 6347 exited (255)

Happens relatively frequently:root@tmate:~# grep FATAL /var/log/tmate-slave.log|ruby -nae 'puts $F[0]'|uniq -c
     50 2015-08-18
    107 2015-08-19
     54 2015-08-20
     58 2015-08-21
     12 2015-08-27
     49 2015-08-28
     78 2015-08-29
    162 2015-08-30
     43 2015-08-31
     54 2015-09-01
     53 2015-09-02
      6 2015-09-03
root@tmate:~#

Doesn't really bother me much systemd restarts it, and it always works when I need to use it.
